# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TableWindow(object):
    def setupUi(self, TableWindow):
        TableWindow.setObjectName("TableWindow")
        TableWindow.resize(850, 600)
        self.centralwidget = QtWidgets.QWidget(TableWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 2, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_2.addWidget(self.pushButton_6, 2, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 2, 1, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.tableWidget, 0, 0, 1, 3)
        TableWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TableWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 850, 18))
        self.menubar.setObjectName("menubar")
        self.menuGo_to_Form = QtWidgets.QMenu(self.menubar)
        self.menuGo_to_Form.setObjectName("menuGo_to_Form")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        TableWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TableWindow)
        self.statusbar.setObjectName("statusbar")
        TableWindow.setStatusBar(self.statusbar)
        self.actionAdd_Item = QtWidgets.QAction(TableWindow)
        self.actionAdd_Item.setObjectName("actionAdd_Item")
        self.actionRemove_Item = QtWidgets.QAction(TableWindow)
        self.actionRemove_Item.setObjectName("actionRemove_Item")
        self.actionSelect_Items = QtWidgets.QAction(TableWindow)
        self.actionSelect_Items.setObjectName("actionSelect_Items")
        self.actionUpdate_Item = QtWidgets.QAction(TableWindow)
        self.actionUpdate_Item.setObjectName("actionUpdate_Item")
        self.actionGo_to_Form = QtWidgets.QAction(TableWindow)
        self.actionGo_to_Form.setObjectName("actionGo_to_Form")
        self.actionOpen = QtWidgets.QAction(TableWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(TableWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuGo_to_Form.addAction(self.actionGo_to_Form)
        self.menuGo_to_Form.addAction(self.actionOpen)
        self.menuGo_to_Form.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionAdd_Item)
        self.menuEdit.addAction(self.actionRemove_Item)
        self.menuEdit.addAction(self.actionSelect_Items)
        self.menuEdit.addAction(self.actionUpdate_Item)
        self.menubar.addAction(self.menuGo_to_Form.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(TableWindow)
        QtCore.QMetaObject.connectSlotsByName(TableWindow)

    def retranslateUi(self, TableWindow):
        _translate = QtCore.QCoreApplication.translate
        TableWindow.setWindowTitle(_translate("TableWindow", "TableWindow"))
        self.pushButton.setText(_translate("TableWindow", "Go to Form"))
        self.pushButton_2.setText(_translate("TableWindow", "Add Item"))
        self.pushButton_3.setText(_translate("TableWindow", "Remove Item"))
        self.pushButton_4.setText(_translate("TableWindow", "Select Items"))
        self.pushButton_6.setText(_translate("TableWindow", "Add Picture"))
        self.pushButton_5.setText(_translate("TableWindow", "Update Item"))
        self.menuGo_to_Form.setTitle(_translate("TableWindow", "File"))
        self.menuEdit.setTitle(_translate("TableWindow", "Edit"))
        self.actionAdd_Item.setText(_translate("TableWindow", "Add Item"))
        self.actionRemove_Item.setText(_translate("TableWindow", "Remove Item"))
        self.actionSelect_Items.setText(_translate("TableWindow", "Select Items"))
        self.actionUpdate_Item.setText(_translate("TableWindow", "Update Item"))
        self.actionGo_to_Form.setText(_translate("TableWindow", "Go to Form"))
        self.actionOpen.setText(_translate("TableWindow", "Open"))
        self.actionExit.setText(_translate("TableWindow", "Exit"))

