# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UpDialog(object):
    def setupUi(self, UpDialog):
        UpDialog.setObjectName("UpDialog")
        UpDialog.resize(500, 400)
        font = QtGui.QFont()
        font.setPointSize(12)
        UpDialog.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(UpDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(UpDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(UpDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(UpDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBox.setFont(font)
        self.spinBox.setMinimum(1970)
        self.spinBox.setMaximum(2025)
        self.spinBox.setProperty("value", 2019)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 5, 2, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(UpDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 8, 2, 1, 2)
        self.lineEdit_3 = QtWidgets.QLineEdit(UpDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 4, 2, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(UpDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonBox.setFont(font)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 9, 3, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(UpDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 2, 2, 1, 2)
        self.lineEdit_4 = QtWidgets.QLineEdit(UpDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 7, 2, 1, 2)
        self.label_7 = QtWidgets.QLabel(UpDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(UpDialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 2, 1, 2)
        self.label_2 = QtWidgets.QLabel(UpDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(UpDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(UpDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(UpDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(UpDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 1, 1, 1)

        self.retranslateUi(UpDialog)
        QtCore.QMetaObject.connectSlotsByName(UpDialog)

    def retranslateUi(self, UpDialog):
        _translate = QtCore.QCoreApplication.translate
        UpDialog.setWindowTitle(_translate("UpDialog", "Обновление"))
        self.label.setText(_translate("UpDialog", "id"))
        self.label_7.setText(_translate("UpDialog", "Комментарий"))
        self.label_2.setText(_translate("UpDialog", "Автор"))
        self.label_3.setText(_translate("UpDialog", "Название"))
        self.label_4.setText(_translate("UpDialog", "Город"))
        self.label_5.setText(_translate("UpDialog", "Год"))
        self.label_6.setText(_translate("UpDialog", "Файл"))

